### ISSUE TITLE
axtls-8266 with non-OS SDK

### ISSUE THREAD

**Issue by rith87** [igrr/axtls-8266#33]
I'm trying to find a light weight SSL library replacement for the one in the non-OS SDK and stumbled across this repo. Is there any way to consume this in the non-OS SDK? I assume I can somehow convert the libaxtls.a into libssl.a..?

**Comment by igrr** [comment]
Not really; libssl also includes a lot of code which ties in espconn and such. You could probably figure out the differences and still reuse this somehow. If you do need specific changes on this library's side, feel free to reopen this or create new issues.
