### ISSUE TITLE
Provide example of using LWIP raw with axTLS

### ISSUE THREAD

**Issue by slaff** [igrr/axtls-8266#5]
It would be great if you can provide examples how to use axTLS with LWIP raw tcp for ESP8266. Even a small source code example will be fine.

**Comment by igrr** [comment]
This library is not compatible with asynchronous raw LwIP APIs. It depends on the following blocking network APIs:

``` c++
#define SOCKET_READ(A,B,C)      ax_port_read(A,B,C)
#define SOCKET_WRITE(A,B,C)     ax_port_write(A,B,C)
#define SOCKET_CLOSE(A)         ax_port_close(A)
```

**Comment by slaff** [comment]
Examples can be found here: https://github.com/igrr/axtls-8266/blob/master/util/README.md
